name: keep_socket_alive
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ^3.6.0

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.8
    socket_io_client: ^3.1.2
    flutter_local_notifications: ^19.1.0
    shared_preferences: ^2.5.3
    workmanager: ^0.5.2
    path_provider: ^2.1.5
    flutter_background_service: ^5.1.0
    flutter_background_service_android: ^6.3.0
    get_it: ^8.0.3
    flutter_foreground_task: ^9.1.0

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^5.0.0

flutter:
    uses-material-design: true
